fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Acme\UserBundle\Entity\User
    service:
        user_manager: pugx_user_manager
    registration:
        form:
        confirmation:
            from_email:
              address:        info@netmeans.net
              sender_name:    nmnMultiUser
            enabled:    true
    profile:
        form:
          
pugx_multi_user:
  users:
    user_one:
        entity: 
          class: Acme\UserBundle\Entity\UserOne
        registration:
          form: Acme\UserBundle\Form\Type\RegistrationUserOneFormType
          options:
            validation_groups: [Registration, Default]
          template: AcmeUserBundle:Registration:user_one.form.html.twig
        profile:
          form: Acme\UserBundle\Form\Type\ProfileUserOneFormType
          options:
            validation_groups: [Profile, Default]
    user_two:
        entity: 
          class: Acme\UserBundle\Entity\UserTwo
#          factory: ~
        registration:
          form: Acme\UserBundle\Form\Type\RegistrationUserTwoFormType
          options:
            validation_groups: [Registration, Default]
          template: AcmeUserBundle:Registration:user_two.form.html.twig
        profile:
          form: Acme\UserBundle\Form\Type\ProfileUserTwoFormType
          options:
            validation_groups: [Profile, Default]
            
#parameters:    
#  pugx_user_discriminator_parameters:
#    classes:
#      UserOne:
#        entity: Acme\UserBundle\Entity\UserOne
#        registration: Acme\UserBundle\Form\Type\RegistrationUserOneFormType
#        registration_options: 
#          validation_groups: [Registration, Default]
#        profile: Acme\UserBundle\Form\Type\ProfileUserOneFormType
#        profile_options: 
#          validation_groups: [Profile, Default]
#        factory: ~
#      UserTwo:
#        entity: Acme\UserBundle\Entity\UserTwo
#        registration: Acme\UserBundle\Form\Type\RegistrationUserTwoFormType
#        registration_options: 
#          validation_groups: [Registration, Default]
#        profile: Acme\UserBundle\Form\Type\ProfileUserTwoFormType
#        profile_options: 
#          validation_groups: [Profile, Default]
#        factory: ~
#        
#      UserThree:
#        entity: 
#          class: Acme\UserBundle\Entity\UserTwo
#          factory: ~
#        registration:
#          form: Acme\UserBundle\Form\Type\RegistrationUserTwoFormType
#          options:
#            validation_groups: [Registration, Default]
#        profile:
#          form: Acme\UserBundle\Form\Type\ProfileUserTwoFormType
#          options:
#            validation_groups: [Profile, Default]